sudo: false
language: node_js
node_js:
  - "8.3"
notifications:
  disabled: true
before_install:
  - openssl aes-256-cbc -K $encrypted_a70933ca97fe_key -iv $encrypted_a70933ca97fe_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
before_deploy:
  - npm run build
deploy:
  provider: gae
  keyfile: gcp-secret.json
  project: app-unityci
  config: app.yaml
  skip_cleanup: true
  verbosity: debug