sudo: false
language: node_js
node_js:
  - "8.3"
notifications:
  disabled: true
before_install:
  - openssl aes-256-cbc -K $encrypted_a70933ca97fe_key -iv $encrypted_a70933ca97fe_iv
  -in gcp-secret.json.enc -out gcp-secret.json -d
deploy:
  provider: gae
  keyfile: gcp-secret.json
  project: app-unityci
  config: app.yaml